---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-nodenetworkoperator-soliddowant-dev-v1alpha1-link
  failurePolicy: Fail
  name: vlink-v1alpha1.kb.io
  rules:
  - apiGroups:
    - nodenetworkoperator.soliddowant.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - links
  sideEffects: None
