# This rule is not used by the project bridge-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to bridgeoperator.soliddowant.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: bridge-operator
    app.kubernetes.io/managed-by: kustomize
  name: link-viewer-role
rules:
- apiGroups:
  - bridgeoperator.soliddowant.dev
  resources:
  - links
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bridgeoperator.soliddowant.dev
  resources:
  - links/status
  verbs:
  - get
