# This rule is not used by the project node-network-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the nodenetworkoperator.soliddowant.dev.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: node-network-operator
    app.kubernetes.io/managed-by: kustomize
  name: link-editor-role
rules:
  - apiGroups:
      - nodenetworkoperator.soliddowant.dev
    resources:
      - links
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - nodenetworkoperator.soliddowant.dev
    resources:
      - links/status
    verbs:
      - get
