---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
- apiGroups:
  - bridgeoperator.soliddowant.dev
  resources:
  - bridges
  - nodebridges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bridgeoperator.soliddowant.dev
  resources:
  - bridges/finalizers
  verbs:
  - patch
- apiGroups:
  - bridgeoperator.soliddowant.dev
  resources:
  - bridges/status
  - nodebridges/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bridgeoperator.soliddowant.dev
  resources:
  - nodebridges/finalizers
  verbs:
  - update
