---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nodenetworkoperator.soliddowant.dev
  resources:
  - links
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nodenetworkoperator.soliddowant.dev
  resources:
  - links/finalizers
  verbs:
  - update
- apiGroups:
  - nodenetworkoperator.soliddowant.dev
  resources:
  - links/status
  - nodelinks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nodenetworkoperator.soliddowant.dev
  resources:
  - nodelinks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - nodenetworkoperator.soliddowant.dev
  resources:
  - nodelinks/finalizers
  verbs:
  - create
  - patch
