---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: gateway-network-client-pods
spec:
  config: |
    {
      "cniVersion": "0.3.0",
      "name": "gateway-network-client-pods",
      "type": "bridge",
      "bridge": "gatewaybridge0",
      "ipam": {
        "type": "whereabouts",
        "range": "192.168.50.0/24",
        "exclude": [
           "192.168.50.1/32"
        ],
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "192.168.50.1"
      },
      "mtu": 1450
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: gateway-network-router-pod
spec:
  config: |
    {
      "cniVersion": "0.3.0",
      "name": "gateway-network-router-pod",
      "type": "bridge",
      "bridge": "gatewaybridge0",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "192.168.50.1/24"
          }
        ]
      },
      "mtu": 1450
    }
